const { isValidObjectId } = require("mongoose");
const User = require("../models/user");
const Audio = require("../models/audio");
const Playlist = require("../models/playlist");
const History = require("../models/history");
const moment = require("moment");
const { getUserPreviusHistory } = require("../utils/helper");
const AutoGeneratedPlaylist = require("../models/autoGeneratedPlaylist");

const updateFollower = async (req, res) => {
  const { profileId } = req.params;
  const { userId } = req.user;

  if (!isValidObjectId(profileId))
    return res.status(422).send({ error: "invalid profile id!" });

  const profile = await User.findById(profileId);

  if (!profile) return res.status(422).send({ error: "profile not found!" });

  const alreadyAFollower = await User.findOne({
    _id: profileId,
    followers: userId,
  });

  let status;

  if (alreadyAFollower) {
    //unfollow
    await User.updateOne({ _id: profileId }, { $pull: { followers: userId } });
    status = "removed";
  } else {
    await User.updateOne(
      { _id: profileId },
      {
        $addToSet: { followers: userId },
      }
    );
    status = "added";
  }

  if (status == "added") {
    await User.updateOne(
      { _id: userId },
      {
        $addToSet: { followings: profileId },
      }
    );
    if (status == "removed") {
      await User.updateOne(
        { _id: userId },
        { $pull: { followings: profileId } }
      );
    }
  }
  res.send({ status });
};

const getUploads = async (req, res) => {
  const { userId } = req.user;
  const { limit = "20", pageNo = "0" } = req.query;

  const data = await Audio.find({ owner: userId })
    .skip(parseInt(limit) * parseInt(pageNo))
    .limit(parseInt(limit))
    .sort("-createdAt");
  if (!data) return res.status(422).send({ error: "audios not found!" });

  const audios = data.map((item) => {
    return {
      id: item._id,
      title: item.title,
      about: item.about,
      file: item.file.url,
      poster: item.poster?.url,
      date: item.createdAt,
      owner: { name: req.user.name, id: userId },
    };
  });
  res.send({ audios });
};

const getPublicUploads = async (req, res) => {
  const { profileId } = req.params;
  const { limit = "20", pageNo = "0" } = req.query;

  if (!isValidObjectId(profileId))
    return res.status(422).send({ error: "invalid profiled Id!" });

  const data = await Audio.find({ owner: profileId })
    .skip(parseInt(limit) * parseInt(pageNo))
    .limit(parseInt(limit))
    .sort("-createdAt")
    .populate({
      path: "owner",
    });
  if (!data) return res.status(422).send({ error: "audios not found!" });

  const audios = data.map((item) => {
    return {
      id: item._id,
      title: item.title,
      about: item.about,
      file: item.file.url,
      poster: item.poster?.url,
      date: item.createdAt,
      owner: { name: item.owner.name, id: item.owner._id },
    };
  });
  res.send({ audios });
};

const getPublicProfile = async (req, res) => {
  const { profileId } = req.params;

  if (!isValidObjectId(profileId))
    res.status(422).send({ error: "invalid profile Id!" });

  const user = await User.findById(profileId);
  if (!user) res.status(422).send({ error: "profile not found!" });

  res.send({
    profile: {
      id: user._id,
      name: user.name,
      followers: user.followers.length,
      avatar: user.avatar?.url,
    },
  });
};

const getPublicPlaylist = async (req, res) => {
  const { profileId } = req.params;
  if (!isValidObjectId(profileId))
    return res.status(422).send({ error: "invalid profile Id!" });

  const playlist = await Playlist.find({
    owner: profileId,
    visibility: "public",
  });
  if (!playlist) return res.send({ playlist: [] });

  res.send({
    playlist: playlist.map((item) => {
      return {
        id: item._id,
        title: item.title,
        itemCount: item.items.length,
        visibility: item.visibility,
      };
    }),
  });
};

const getRecommandedAudios = async (req, res) => {
  const userId = req.user?.userId;

  let matchOptions = { $match: { _id: { $exists: true } } };
  if (userId) {
    const categories = await getUserPreviusHistory(req);

    if (categories.length) {
      matchOptions = {
        $match: { category: { $in: categories } },
      };
    }
  }

  const audios = await Audio.aggregate([
    matchOptions,
    {
      $sort: { "likes.count": -1 },
    },
    { $limit: 10 },
    {
      $lookup: {
        from: "users",
        localField: "owner",
        foreignField: "_id",
        as: "owner",
      },
    },
    {
      $unwind: "$owner",
    },
    {
      $project: {
        _id: 0,
        id: "$_id",
        title: "$title",
        about: "$abut",
        category: "$category",
        file: "$file.url",
        poster: "$poster.url",
        owner: {
          name: "$owner.name",
          id: "$owner._id",
        },
      },
    },
  ]);

  res.send(audios);
};

const getAutoGeneratedPlaylist = async (req, res) => {
  ///mix 20

  const [result] = await History.aggregate([
    { $match: { owner: req.user.userId } },
    { $unwind: "$all" },
    { $group: { _id: "$all.audio", items: { $addToSet: "$all.audio" } } },
    { $sample: { size: 20 } },
    { $group: { _id: 0, items: { $push: "$_id" } } },
  ]);

  let title = "mix 20";

  if (result) {
    await Playlist.updateOne(
      {
        owner: req.user.userId,
        title,
      },
      { $set: { title, items: result.items, visibility: "auto" } },
      { upsert: true }
    );
  }

  /// auto  generated playlist
  const histoires = await getUserPreviusHistory(req);

  let matchOptions = { $match: { _id: { $exists: true } } };

  if (histoires.length) {
    matchOptions = { $match: { title: { $in: histoires.category } } };
  }

  const agpl = await AutoGeneratedPlaylist.aggregate([
    matchOptions,
    {
      $sample: { size: 20 },
    },
    {
      $project: {
        _id: 0,
        id: "$_id",
        tiltle: "$title",
        itemCount: { $size: "$items" },
      },
    },
  ]);

  const [playlist] = await Playlist.find({ owner: req.user.userId, title });

  const finalList = agpl.concat({
    id: playlist?._id,
    title: playlist?.title,
    itemCount: playlist?.items.length,
  });

  res.send(finalList);
};

module.exports = {
  updateFollower,
  getUploads,
  getPublicUploads,
  getPublicProfile,
  getPublicPlaylist,
  getRecommandedAudios,
  getAutoGeneratedPlaylist,
};
