const { Schema, models, model, SchemaType, SchemaTypes } = require("mongoose");

const autoGeneratedPlaylistSchema = new Schema(
  {
    title: {
      type: String,
      required: true,
    },

    items: [{ type: Schema.Types.ObjectId, ref: "Audio", required: true }],
  },
  { timestamps: true }
);

module.exports =
  models.autoGeneratedPlaylist ||
  model("autoGeneratedPlaylist", autoGeneratedPlaylistSchema);
