const { Router } = require("express");
const isAuth = require("../middleware/isAuth");
const isVerified = require("../middleware/isVerified");
const {
  updateFollower,
  getUploads,
  getPublicUploads,
  getPublicProfile,
  getPublicPlaylist,
  getRecommandedAudios,
  getFollowersProfile,
} = require("../controllers/profileController");
const { checkout } = require("./auth");
const checkAuth = require("../middleware/checkAuth");
const {
  getAutoGeneratedPlaylist,
} = require("../controllers/profileController");

const router = Router();

router.post("/update-follower/:profileId", isAuth, isVerified, updateFollower);
router.get("/uploads", isAuth, getUploads);
router.get("/uploads/:profileId", getPublicUploads);
router.get("/info/:profileId", getPublicProfile);
router.get("/playlist/:profileId", getPublicPlaylist);

router.get("/recommanded", checkAuth, getRecommandedAudios);
router.get("/get-autoGenerated-playlist", isAuth, getAutoGeneratedPlaylist);

router.get("/getFollowers", isAuth, getFollowersProfile);
module.exports = router;
